"""Add DocumentChunk model and update Document for RAG document management

Revision ID: 4e7c40378a1a
Revises: 1651e11a8e22
Create Date: 2026-02-28 12:47:22.438435

"""
from collections.abc import Sequence

import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4e7c40378a1a'
down_revision: str | Sequence[str] | None = '1651e11a8e22'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Create DocumentChunk table first
    op.create_table('document_chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(dim=1536), nullable=False),
    sa.Column('chunk_metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)

    # Drop old pages table
    op.drop_index(op.f('ix_pages_nombre_archivo'), table_name='pages')
    op.drop_table('pages')

    # Update documents table: add new columns as nullable first
    op.add_column('documents', sa.Column('file_type', sa.String(length=50), nullable=True))
    op.add_column('documents', sa.Column('school', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('file_url', sa.String(length=1000), nullable=True))
    op.add_column('documents', sa.Column('is_active', sa.Boolean(), nullable=True))

    # Set default values for existing rows
    op.execute("UPDATE documents SET file_type = 'pdf', school = 'Información General', file_url = '', is_active = true WHERE file_type IS NULL")

    # Alter columns to NOT NULL
    op.alter_column('documents', 'file_type', existing_type=sa.String(length=50), nullable=False)
    op.alter_column('documents', 'school', existing_type=sa.String(length=255), nullable=False)
    op.alter_column('documents', 'file_url', existing_type=sa.String(length=1000), nullable=False)
    op.alter_column('documents', 'is_active', existing_type=sa.Boolean(), nullable=False)

    # Manage indexes
    op.drop_index(op.f('ix_documents_tipo'), table_name='documents')
    op.create_index('idx_document_school', 'documents', ['school'], unique=False)
    op.create_index(op.f('ix_documents_school'), 'documents', ['school'], unique=False)

    # Drop old column
    op.drop_column('documents', 'tipo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('tipo', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_documents_school'), table_name='documents')
    op.drop_index('idx_document_school', table_name='documents')
    op.create_index(op.f('ix_documents_tipo'), 'documents', ['tipo'], unique=False)
    op.drop_column('documents', 'is_active')
    op.drop_column('documents', 'file_url')
    op.drop_column('documents', 'school')
    op.drop_column('documents', 'file_type')
    op.create_table('pages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('nombre_archivo', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('pagina', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pages_pkey'))
    )
    op.create_index(op.f('ix_pages_nombre_archivo'), 'pages', ['nombre_archivo'], unique=False)
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    # ### end Alembic commands ###
